# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20170614_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
                ('name', models.CharField(max_length=128, verbose_name='\u7ec4\u540d')),
                ('description', models.TextField(verbose_name='\u7ec4\u63cf\u8ff0')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
                ('name', models.CharField(max_length=128, verbose_name='\u6743\u9650\u540d')),
                ('description', models.TextField(verbose_name='\u6743\u9650\u63cf\u8ff0')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Permission_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
                ('permissionId', models.IntegerField(verbose_name='\u6743\u9650id')),
                ('groupId', models.IntegerField(verbose_name='\u7ec4id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
                ('users', models.CharField(max_length=128, verbose_name='\u767b\u5f55\u540d')),
                ('passwd', models.CharField(max_length=128, verbose_name='\u5bc6\u7801')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('city', models.CharField(max_length=32, verbose_name='\u57ce\u5e02')),
                ('email', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('phone', models.CharField(max_length=32, verbose_name='\u7535\u8bdd')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
                ('userId', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('groupId', models.IntegerField(verbose_name='\u7ec4id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User_Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_flag', models.CharField(max_length=4, verbose_name='\u5220\u9664\u6807\u5fd7')),
                ('userId', models.IntegerField(verbose_name='\u7528\u6237id')),
                ('permissionId', models.IntegerField(verbose_name='\u6743\u9650id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
